# workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  deploy: 
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3	
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive) 
          fetch-depth: 0 

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2	
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo -d ./docs --minify	

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./docs

