# workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  deploy: 
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4	
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive) 
          fetch-depth: 0 

      # - name: Setup pnpm
      #   uses: pnpm/action-setup@v4
      #   with:
      #     version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'  
          # cache: 'pnpm'

      # - name: Install dependencies
      #   run: pnpm install

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3	
        with:
          # hugo-version: 'latest'
          hugo-version: '0.145.0'
          extended: true

      - name: Build
        run: hugo --minify	

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./docs
          #cname: faimin.com

